name: basehttp
description: Flutter网络基础库.
version: 0.0.1
author: Scott Wang
homepage: https://github.com/flutter-my-package/flutter-base-http

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter